[[collection]]
type="box"
img="/assets/g1.jpeg"
link="https://sweetjing.cc"
rotate=true
title="半截の诗"
subtitle="保持热爱，奔赴山海。"

[[collection]]
type="box"
img="/assets/g2.jpeg"
link="https://www.xiaoa.me"
rotate=true
title="半日闲"
subtitle="偷得浮生半日闲"

[[collection]]
type="box"
img="/assets/box-12.jpg"
link="https://eyu.at"
rotate=true
title="鹅玉"
subtitle="很有趣的博客"

[[collection]]
type="box"
img="/assets/g3.ico"
link="https://www.creammint.cn"
rotate=true
title="薄荷の半亩"
subtitle="在这半亩田地里，不疾不徐，记录每一次生长。"
