[[collection]]
type = "entry"
link = "https://www.rust-lang.org"
icon = "https://cdn.simpleicons.org/rust"
desc = "Rust"

[[collection]]
type = "entry"
link = "https://www.anaconda.com"
icon = "https://cdn.simpleicons.org/anaconda"
desc = "Anaconda"

[[collection]]
type = "entry"
link = "https://archlinux.org"
icon = "https://cdn.simpleicons.org/archlinux"
desc = "Arch Linux"

[[collection]]
type = "entry"
link = "https://www.gnu.org/software/bash"
icon = "https://cdn.simpleicons.org/gnubash"
desc = "Bash"

[[collection]]
type = "entry"
link = "https://bun.sh"
icon = "https://cdn.simpleicons.org/bun"
desc = "Bun"

[[collection]]
type = "entry"
link = "https://isocpp.org"
icon = "https://cdn.simpleicons.org/cplusplus"
desc = "C++"

[[collection]]
type = "entry"
link = "https://www.debian.org"
icon = "https://cdn.simpleicons.org/debian"
desc = "Debian"

[[collection]]
type = "entry"
link = "https://deno.com"
icon = "https://cdn.simpleicons.org/deno"
desc = "Deno"

[[collection]]
type = "entry"
link = "https://www.docker.com"
icon = "https://cdn.simpleicons.org/docker"
desc = "Docker"

[[collection]]
type = "entry"
link = "https://git-scm.com"
icon = "https://cdn.simpleicons.org/git"
desc = "Git"

[[collection]]
type = "entry"
link = "https://github.com"
icon = "https://cdn.simpleicons.org/github"
desc = "GitHub"

[[collection]]
type = "entry"
link = "https://developer.mozilla.org/docs/Web/JavaScript"
icon = "https://cdn.simpleicons.org/javascript"
desc = "JavaScript"

[[collection]]
type = "entry"
link = "https://www.kernel.org"
icon = "https://cdn.simpleicons.org/linux"
desc = "Linux"

[[collection]]
type = "entry"
link = "https://neovim.io"
icon = "https://cdn.simpleicons.org/neovim"
desc = "Neovim"

[[collection]]
type = "entry"
link = "https://www.typescriptlang.org"
icon = "https://cdn.simpleicons.org/typescript"
desc = "TypeScript"

[[collection]]
type = "entry"
link = "https://webassembly.org"
icon = "https://cdn.simpleicons.org/webassembly"
desc = "WebAssembly"

[[collection]]
type = "entry"
link = "https://www.tensorflow.org"
icon = "https://cdn.simpleicons.org/tensorflow"
desc = "TensorFlow"

[[collection]]
type = "entry"
link = "https://www.python.org"
icon = "https://cdn.simpleicons.org/python"
desc = "Python"

[[collection]]
type = "entry"
link = "https://obsidian.md"
icon = "https://cdn.simpleicons.org/obsidian"
desc = "Obsidian"

[[collection]]
type = "entry"
link = "https://www.markdownguide.org"
icon = "https://cdn.simpleicons.org/markdown"
desc = "Markdown"

[[collection]]
type = "entry"
link = "https://www.latex-project.org"
icon = "https://cdn.simpleicons.org/latex"
desc = "LaTeX"

[[collection]]
type = "entry"
link = "https://www.cloudflare.com"
icon = "https://cdn.simpleicons.org/cloudflare"
desc = "Cloudflare"

[[collection]]
type = "entry"
link = "https://zed.dev"
icon = "https://cdn.simpleicons.org/zedindustries"
desc = "Zed"
