[[collection]]
type = "art_simple"
img = "https://cdn.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c1.webp"
link = "https://pan.quark.cn/s/e236d3e0b613"
code = "提取码：ZhFT"
title = "年年的高雅集"

[[collection]]
type = "art_simple"
img = "https://fastly.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c2.webp"
link = "https://mypikpak.com/s/VOw5ubZW7CNXy-Fk9WWt_41Do2"
code = "pikpak"
title = "小鹿鹿 - Dokidoki2"

[[collection]]
type = "art_simple"
img = "https://cdn.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c3.webp"
link = "https://mypikpak.com/s/VOw5zSHu7CNXy-Fk9WWtaf3Ho2"
code = "pikpak"
title = "桜桃喵 - 蓝"

[[collection]]
type = "art_simple"
img = "https://fastly.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c4.webp"
link = "https://mypikpak.com/s/VOw60imO4ZMXG1flMxUHgQDno2"
code = "pikpak"
title = "White Bodysuit"

[[collection]]
type = "art_simple"
img = "https://cdn.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c5.webp"
link = "https://mypikpak.com/s/VOw63APRN4NaWrtnMaidX_H0o2"
code = "pikpak"
title = "White See through"

[[collection]]
type = "art_simple"
img = "https://gcore.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c6.webp"
link = "https://mypikpak.com/s/VOw64V_EKYaTvLJ4gr2ie70vo2"
code = "pikpak"
title = "Terrace"

[[collection]]
type = "art_simple"
img = "https://cdn.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c7.webp"
link = "https://mypikpak.com/s/VOw65FaKN4NaWrtnMaidYGVBo2"
code = "pikpak"
title = "MoonNightSnap"

[[collection]]
type = "art_simple"
img = "https://cdn.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c8.webp"
link = "https://mypikpak.com/s/VOw68RlKKYaTvLJ4gr2ifRgRo2"
code = "pikpak"
title = "In Tokyo"

[[collection]]
type = "art_simple"
img = "https://cdn.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c9.webp"
link = "https://mypikpak.com/s/VOw69USYNJ3lhc4GTNRfvVqCo2"
code = "pikpak"
title = "桜桃喵 199"

[[collection]]
type = "art_simple"
img = "https://gcore.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/portrait/c10.webp"
link = "https://2000python.lanzouq.com/isvuG1sqjicf"
code = "解压码：奥山"
title = "奥山和纱 Clear"
