[[collection]]
type="box"
img="https://gcore.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/collection/store.png"
link="https://storeweb.cn"
rotate=true
title="个站商店"
subtitle="一个精致的，带社交元素的个人网站发布平台，博客收录网站。"

[[collection]]
type="box"
img="https://gcore.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/collection/club.png"
link="https://www.blogsclub.org"
rotate=true
title="BlogsClub"
subtitle="独立且相互包容的个人博客俱乐部。"

[[collection]]
type="box"
img="https://gcore.jsdelivr.net/gh/rainsins/blog-npm-source@main/img/collection/ten.ico"
link="https://www.foreverblog.cn"
rotate=true
title="十年之约"
subtitle="一个人的寂寞，一群人的狂欢。"
